- name: "Install apps"
  hosts: win
  tasks:
    - name: Install apps via chocolately
      win_chocolatey:
          name:
           - git
           - spotify
           - conemu
           - openssh
           - greenshot
           - vlc
           - steam-client
           - googlechrome
           - discord
           - zoom
           - everything
           - vscode 
           - 7zip
           - origin
           - goggalaxy
           - python3
           - nodejs.install
           - foxitreader
           - paint.net
           - nvidia-display-driver
           - authy-desktop
          state: latest
    - name: Install nvidia broadcast
      ansible.windows.win_package:
        path: https://international.download.nvidia.com/Windows/broadcast/1.2.0/NVIDIA_Broadcast_v1.2.0.49.exe
