- name: UpdateWindows
  hosts: win
  tasks:
     - name: Update windows hosts
       win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        reboot: true