kubernetes_version: '1.26'
kubernetes_version_rhel_package: '1.26.0'
kubernetes_version_kubeadm: 'stable-{{ kubernetes_version }}'

kubernetes_packages:
  - name: kubelet
    state: present
  - name: kubectl
    state: present
  - name: kubeadm
    state: present
  - name: kubernetes-cni
    state: present

lsb_id: "{{ ansible_lsb.id }}"

kubernetes_apiserver_advertise_address: '' #Blank so it defaults to my ethernet ip

kubernetes_apt_release_channel: main
kubernetes_apt_repository: "deb http://apt.kubernetes.io/ kubernetes-xenial {{ kubernetes_apt_release_channel }}"

kubernetes_config_init_configuration:
  localAPIEndpoint:
    advertiseAddress: "{{ kubernetes_apiserver_advertise_address }}"

kubernetes_config_cluster_configuration:
  networking:
    podSubnet: "{{ kubernetes_pod_network.cidr }}"
  kubernetesVersion: "{{ kubernetes_version_kubeadm }}"

kubernetes_config_kube_proxy_configuration: {}

kubernetes_pod_network:
  cni: 'calico'
  cidr: '10.250.0.0/16'

kubernetes_calico_manifest_file: https://projectcalico.docs.tigera.io/manifests/calico.yaml

kubernetes_kubeadm_kubelet_config_file_path: '/etc/kubernetes/kubeadm-kubelet-config.yaml'
kubernetes_config_kubelet_configuration:
  cgroupDriver: "systemd"

kubernetes_allow_pods_on_control_plane: true

kubernetes_ignore_preflight_errors: 'all'

#Optional
kubernetes_kubeadm_init_extra_opts: ""
kubernetes_join_command_extra_opts: ""
