- name: "Install node version manager"
  hosts: linux
  become: true
  become_user: root
  tasks:
    - name: Download node
      get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh
        dest: /tmp/nvm.sh
        mode: '0400'
    - name: install node version manager
      ansible.builtin.script:
        cmd: /tmp/nvm.sh