---

- hosts: all

  tasks:
    - name: Set a hostname
      hostname:
        name: "{{ inventory_hostname }}"
      become: yes
      become_method: sudo

    - name: Change the host name
      become: yes
      replace:
        path: /etc/hosts
        regexp: '^(127\.0\.[0|1]\.1).*'
        replace: '\1 localhost {{ inventory_hostname }}'