---

- name: Ensure dependencies are installed.
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
    state: present

- name: Add Docker apt key.
  become: true
  apt_key:
    url: "{{ docker_apt_gpg_key }}"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: true #Yolo

- name: Add Docker repository.
  become: true
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true
